default_repo := 'nilscan'

build repo=default_repo:
  docker build -t {{repo}}/terragrunt-runner:0.0.0 .

push repo=default_repo:
  docker push {{repo}}/terragrunt-runner:0.0.0

publish repo=default_repo: (build repo) (push repo)
