apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "terraform-job.name" . }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation # Keep the job until we need to run a new one
  labels:
    managed-by: {{ .Values.managedBy }}
spec:
  template:
    metadata:
      labels:
        managed-by: {{ .Values.managedBy }}
    spec:
      containers:
        - name: tf
          image: {{ if .Values.easyaas.docker.registry }}{{ .Values.easyaas.docker.registry }}/{{end}}{{ .Values.easyaas.docker.image }}:{{ .Values.easyaas.docker.tag }}
          imagePullPolicy: Always # Import images with just import-docker
          env:
            - name: TERRAGRUNT_CONFIG
              value: {{ default .Values.easyaasResourceParams.terragruntFile "/app/terragrunt-config/terragrunt.hcl" }}
            - name: TERRAGRUNT_ACTION
              value: apply
          volumeMounts:
            - name: terragrunt-config
              mountPath: /app/terragrunt-config
      serviceAccountName: {{ template "serviceAccount.name" . }}
      restartPolicy: Never
      volumes:
        - name: terragrunt-config
          configMap:
            name:  {{ .Release.Name }}-{{ .Release.Revision }}
  backoffLimit: 0
  ttlSecondsAfterFinished: null # Job will be deleted on the next helm run as per helm.sh/hook-delete-policy
